load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "orientation_handler",
    srcs = ["orientation_handler.cpp"],
    hdrs = ["orientation_handler.h"],
    visibility = ["//lib:__subpackages__"],
    deps = ["//lib/point:point","//lib/direction:direction"],
)