load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "file_manager",
    srcs = ["file_manager.cpp"],
    hdrs = ["file_manager.h"],
    visibility = ["//lib:__subpackages__"],
    deps = ["//lib/point:point"],
)